export const FETCH_TRENDING_MOVIES_START = "FETCH_TRENDING_MOVIES_START";
export const FETCH_TRENDING_MOVIES_SUCCESS = "FETCH_TRENDING_MOVIES_SUCCESS";
export const FETCH_TRENDING_MOVIES_FAIL = "FETCH_TRENDING_MOVIES_FAIL";

export const FETCH_MOVIES_UPCOMING_START = "FETCH_MOVIES_UPCOMING_START";
export const FETCH_MOVIES_UPCOMING_SUCCESS = "FETCH_MOVIES_UPCOMING_SUCCESS";
export const FETCH_MOVIES_UPCOMING_FAIL = "FETCH_MOVIES_UPCOMING_FAIL";

export const FETCH_MOVIES_NOW_PLAYING_START = "FETCH_MOVIES_NOW_PLAYING_START";
export const FETCH_MOVIES_NOW_PLAYING_SUCCESS = "FETCH_MOVIES_NOW_PLAYING_SUCCESS";
export const FETCH_MOVIES_NOW_PLAYING_FAIL = "FETCH_MOVIES_NOW_PLAYING_FAIL";

export const FETCH_MOVIES_POPULAR_START = "FETCH_MOVIES_POPULAR_START";
export const FETCH_MOVIES_POPULAR_SUCCESS = "FETCH_MOVIES_POPULAR_SUCCESS";
export const FETCH_MOVIES_POPULAR_FAIL = "FETCH_MOVIES_POPULAR_FAIL";

export const FETCH_MOVIES_TOP_RATED_START = "FETCH_MOVIES_TOP_RATED_START";
export const FETCH_MOVIES_TOP_RATED_SUCCESS = "FETCH_MOVIES_TOP_RATED_SUCCESS";
export const FETCH_MOVIES_TOP_RATED_FAIL = "FETCH_MOVIES_TOP_RATED_FAIL";