export const FETCH_TRENDING_MOVIES_START = "FETCH_TRENDING_MOVIES_START";
export const FETCH_TRENDING_MOVIES_SUCCESS = "FETCH_TRENDING_MOVIES_SUCCESS";
export const FETCH_TRENDING_MOVIES_FAIL = "FETCH_TRENDING_MOVIES_FAIL";
//----------------------------------------------------------------------------------------
export const FETCH_MOVIES_UPCOMING_START = "FETCH_MOVIES_UPCOMING_START";
export const FETCH_MOVIES_UPCOMING_SUCCESS = "FETCH_MOVIES_UPCOMING_SUCCESS";
export const FETCH_MOVIES_UPCOMING_FAIL = "FETCH_MOVIES_UPCOMING_FAIL";

export const FETCH_MOVIES_NOW_PLAYING_START = "FETCH_MOVIES_NOW_PLAYING_START";
export const FETCH_MOVIES_NOW_PLAYING_SUCCESS = "FETCH_MOVIES_NOW_PLAYING_SUCCESS";
export const FETCH_MOVIES_NOW_PLAYING_FAIL = "FETCH_MOVIES_NOW_PLAYING_FAIL";

export const FETCH_MOVIES_POPULAR_START = "FETCH_MOVIES_POPULAR_START";
export const FETCH_MOVIES_POPULAR_SUCCESS = "FETCH_MOVIES_POPULAR_SUCCESS";
export const FETCH_MOVIES_POPULAR_FAIL = "FETCH_MOVIES_POPULAR_FAIL";

export const FETCH_MOVIES_TOP_RATED_START = "FETCH_MOVIES_TOP_RATED_START";
export const FETCH_MOVIES_TOP_RATED_SUCCESS = "FETCH_MOVIES_TOP_RATED_SUCCESS";
export const FETCH_MOVIES_TOP_RATED_FAIL = "FETCH_MOVIES_TOP_RATED_FAIL";
// ----------------------------------------------------------------------------------------
export const FETCH_TV_POPULAR_START = "FETCH_TV_POPULAR_START";
export const FETCH_TV_POPULAR_SUCCESS = "FETCH_TV_POPULAR_SUCCESS";
export const FETCH_TV_POPULAR_FAIL = "FETCH_TV_POPULAR_FAIL";

export const FETCH_TV_AIRING_TODAY_START = "FETCH_TV_AIRING_TODAY_START";
export const FETCH_TV_AIRING_TODAY_SUCCESS = "FETCH_TV_AIRING_TODAY_SUCCESS";
export const FETCH_TV_AIRING_TODAY_FAIL = "FETCH_TV_AIRING_TODAY_FAIL";

export const FETCH_TV_ON_THE_AIR_START = "FETCH_TV_ON_THE_AIR_START";
export const FETCH_TV_ON_THE_AIR_SUCCESS = "FETCH_TV_ON_THE_AIR_SUCCESS";
export const FETCH_TV_ON_THE_AIR_FAIL = "FETCH_TV_ON_THE_AIR_FAIL";

export const FETCH_TV_TOP_RATED_START = "FETCH_TV_TOP_RATED_START";
export const FETCH_TV_TOP_RATED_SUCCESS = "FETCH_TV_TOP_RATED_SUCCESS";
export const FETCH_TV_TOP_RATED_FAIL = "FETCH_TV_TOP_RATED_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_TV_GENRE_LIST_START = "FETCH_TV_GENRE_LIST_START";
export const FETCH_TV_GENRE_LIST_SUCCESS = "FETCH_TV_GENRE_LIST_SUCCESS";
export const FETCH_TV_GENRE_LIST_FAIL = "FETCH_TV_GENRE_LIST_FAIL";

export const FETCH_MOVIE_GENRE_LIST_START = "FETCH_MOVIE_GENRE_LIST_START";
export const FETCH_MOVIE_GENRE_LIST_SUCCESS = "FETCH_MOVIE_GENRE_LIST_SUCCESS";
export const FETCH_MOVIE_GENRE_LIST_FAIL = "FETCH_MOVIE_GENRE_LIST_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_TV_DISCOVER_START = "FETCH_TV_DISCOVER_START";
export const FETCH_TV_DISCOVER_SUCCESS = "FETCH_TV_DISCOVER_SUCCESS";
export const FETCH_TV_DISCOVER_FAIL = "FETCH_TV_DISCOVER_FAIL";

export const FETCH_MOVIE_DISCOVER_START = "FETCH_MOVIE_DISCOVER_START";
export const FETCH_MOVIE_DISCOVER_SUCCESS = "FETCH_MOVIE_DISCOVER_SUCCESS";
export const FETCH_MOVIE_DISCOVER_FAIL = "FETCH_MOVIE_DISCOVER_FAIL";
//------------------------------------------------------------------------------------------