export const FETCH_TRENDING_MOVIES_START = "FETCH_TRENDING_MOVIES_START";
export const FETCH_TRENDING_MOVIES_SUCCESS = "FETCH_TRENDING_MOVIES_SUCCESS";
export const FETCH_TRENDING_MOVIES_FAIL = "FETCH_TRENDING_MOVIES_FAIL";